version: '2.1'

services:
  cassandra:
    container_name: cassandra
    image: intezer/cassandra-dev:3.11.3
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50

  rabbit:
    container_name: rabbit
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  app_dramatiq:
    container_name: app_dramatiq
    build: .
    depends_on:
      cassandra:
        condition: service_healthy
    command: "dramatiq manager"

  app:
    container_name: app
    build: .
    ports:
      - 5000:5000
    depends_on:
      cassandra:
        condition: service_healthy
    command: "flask run"